### ISSUE TITLE
Feature Request: Bulk user addition

### ISSUE THREAD

**Issue by Infthitbox** [uhm-coe/authorizer#10]
We'd like a feature to bulk add users to a site, by copying in a list of many usernames or email addresses with the same role and submitting them all at once.

**Comment by figureone** [comment]
I plan on integrating this into the Access Lists settings page. You'll be able to paste multiple email addresses (separated by spaces) into the new user textbox, and they will all get added. Does that sound workable?

**Comment by Infthitbox** [comment]
Yeah, that's what I'm thinking of. Probably a text box where each line (or arbitrary whitespace delimiter) is an email address and a dropdown for the role of the whole list.

**Comment by BryantD** [comment]
I'm highly interested in this feature -- if you have a bounty system I'd be more than happy to chip in on this one.

**Comment by figureone** [comment]
Cool, thanks for the feedback. We don't currently have a bounty system, but this feature is at the top of our list, along with paged user lists. Will keep you updated!

**Comment by figureone** [comment]
This feature should make it into the next release.
https://github.com/uhm-coe/authorizer/commit/dfddedb3a24b8e3347cd774bb1b8e8d64c81d104

**Comment by pkarjala** [comment]
@BryantD We are pleased to announce the multiple user addition is now available in Authorizer 2.7.0.  Users may be added separated by newlines, spaces, commas, or semicolons.

Please see https://github.com/uhm-coe/authorizer/blob/master/readme.txt for the full changelog.
