### ISSUE TITLE
Oaut2.0

### ISSUE THREAD

**Issue by washidepl** [uhm-coe/authorizer#101]
After  i've set up  plugin  with ouath2.0 on cas-overlay  i have possibility click on oauth buton on  https:/prg.example.org/wp-admin  page . But after i clicked  i was  moved to:

https://prg.example.org/https;/sso.example.org/casphp/oauth2.0/authorize/?state=...etc...

It is sth no ok becouse i have got   endpoinds setuped  to http://sso.expample.org no **http;/**    and  of course  is not setuped to :
https://prg.example.org/https;/sso.example.org/casphp/oauth2.0/authorize/?state=...etc...

lastversion of authorizer

**Comment by figureone** [comment]
Could you clarify? Most of those URLs look invalid, so I'm not sure what's a typo and what's not.

**Comment by figureone** [comment]
Best guess is you have a typo in your **Authorization URL** field in Authorizer settings; since `https;/` is not a valid protocol, it's interpreting the URL as a relative path and appending it to the current URL root.
