### ISSUE TITLE
This plugin is compatible with wp-oauth ?

### ISSUE THREAD

**Issue by abnerjacobsen** [uhm-coe/authorizer#106]
Hi, 

I'm trying to use authorizer using an custom OAUTH server create usin this wordpress plugin https://wp-oauth.com/.

I have wpsite_A actings as an OAUTH server using https://wp-oauth.com/ and another wp  and wpsite_B site were I installed authorizer.

When I go to wpsite_B login page and ask to use authorizer SSO I get redirect to wpsite_A login page, fill user/password fields and when redirected to wpsite_B, after successfull login, I got these warnings:

```
Warning: explode() expects parameter 2 to be string, array given in /home/343858.cloudwaysapps.com/cwtzgadggz/public_html/wp-content/plugins/authorizer/src/authorizer/class-authentication.php on line 584

 Warning: current() expects parameter 1 to be array, null given in /home/343858.cloudwaysapps.com/cwtzgadggz/public_html/wp-content/plugins/authorizer/src/authorizer/class-authentication.php on line 584
```

And in the login page o wpsite_B the login is denied with this message:

**Cannot create a user with empty username.**

Any idea how to solve this problem ?

Thanks,

**Comment by figureone** [comment]
Aloha, thanks for providing wp-oauth.com testing. We have found and fixed the bug, and a new release will be out shortly, version `3.2.1`. Please test when that happens and let us know if it fixes your issue. Thanks!
https://github.com/uhm-coe/authorizer/commit/ba7ee58dcbe1d8c8b049a0fe1cea9fa1287b6bb1
