### ISSUE TITLE
Just updated to version 3.2.1 and I now can't log in

### ISSUE THREAD

**Issue by dbarczak1** [uhm-coe/authorizer#107]
Hello Paul,
I am having a hard time logging in since your "Authorizer" 3.2.1 update. My host is Pantheon and "Authorizer" has been working great for the last few years but something happened since your current update. Is there a way to install the older version?

db@udel.edu

**Comment by figureone** [comment]
Yeah, scroll to the bottom of this page and there's a dropdown for older versions:
https://wordpress.org/plugins/authorizer/advanced/

Once you get things back up and running, please check the Pantheon error logs and let us know if you see anything relevant!

**Comment by dbarczak1** [comment]
Thanks Paul! I really appreciate it.

You have a great product! For a person who knows very little about CAS login you make it easy to get it up and working in no time.

Dave

**Comment by figureone** [comment]
Aloha and Happy New Year!

Just checking in to see if you found any messages in the Pantheon PHP Error Log related to Authorizer. If so we can try to track down any issues with the latest version.
