### ISSUE TITLE
Renew session and Ajax 

### ISSUE THREAD

**Issue by wixaw** [uhm-coe/authorizer#110]
Hello
First of all, your plugin is great! We use for a CAS Connection.
The site is an intranet, all pages are therefore authenticated
We have created request forms, these forms are in AJAX
Some have many fields and can be written during the day, started in the morning and submitted in the afternoon.
We have the impression that the sessions via Authorizer expire, indeed the forms use wp_get_current_user to retrieve name information, mail etc. And sessions that haven't been refreshed in between have these empty objects
How could I code a refresh session?
I tried a simple call of authorizer.php in include it did nothing
I wanted to do a $_SESSION, with username and id to do a 'wp_set_current_user' but your plugin seems to do a destroy_session and delete this session
Thank you for your help
William

**Comment by figureone** [comment]
Aloha, after authenticating with an external service, Authorizer actually isn't involved anymore; the user is simply logged in to their WordPress account. You can adjust the time before the WordPress login cookie expires using the `auth_cookie_expiration` hook:
https://developer.wordpress.org/reference/hooks/auth_cookie_expiration/

By default, WordPress expires a session after 2 days (14 days if the "remember me" checkbox is checked in wp-login.php, but Authorizer currently ignores "remember me").
https://developer.wordpress.org/reference/functions/wp_set_auth_cookie/

My other comment is that if you are using nonces in your AJAX handlers (good security practice), then you might want to also increase the time before nonces expire. By default, they expire between 12–24 hours after creation. So if you leave a browser tab open for 12+ hours, your AJAX handlers might be failing on nonce verification.
https://wordpress.stackexchange.com/questions/237581/maximum-lifetime-for-nonce
https://developer.wordpress.org/reference/hooks/nonce_life/

**Comment by wixaw** [comment]
Hello
thank you for your reply
I have already read how cookies work but we are rather in error after 4/5 hours of inactivity so we are not in this situation. I did a grep of auth_cookie_expiration to see if nothing else could modify this value and it is not.

If during the submit, I do a dump of the sessions, I get this:
Array ( [phpCAS] => Array ( [user] => myuser [attributes] => Array ( [credentialType] => RememberMeUsernamePasswordCredential [isFromNewLogin] => false [mail] => mymail@domain.com [authenticationDate] => 2022 -03-30T07:01:27.065991Z [authenticationMethod] => LdapAuthenticationHandler [givenName] => William [successfulAuthenticationHandlers] => LdapAuthenticationHandler [longTermAuthenticationRequestTokenUsed] => false [cn] => Vincent William [sn] => Vincent ) ) )
So I guess the authorizer/CAS is still involved

And no I am not using a nonce precisely to simplify the process

**Comment by figureone** [comment]
phpCAS (the library doing the CAS authentication) may leave its session data around, but Authorizer only calls phpCAS in the `authenticate` and `wp_logout` hooks. So there shouldn't ever be a round trip to the CAS server unless the WordPress session itself times out (see the previous answer for when that happens).
https://developer.wordpress.org/reference/hooks/authenticate/
https://developer.wordpress.org/reference/hooks/wp_logout/

Also, Authorizer itself only calls `session_start()` for OAuth2 logins and Google logins/logouts (to resume their session and fetch the data stored there).

So if your WordPress sessions are ending after 4/5 hours, maybe look around for other code that might be logging out the WordPress user:
https://developer.wordpress.org/reference/functions/wp_logout/
https://developer.wordpress.org/reference/functions/wp_destroy_current_session/
https://developer.wordpress.org/reference/functions/wp_clear_auth_cookie/
https://developer.wordpress.org/reference/functions/wp_set_current_user/

Or, alternatively, your own management of `$_SESSION` might be accidentally deleting the WordPress session token, so it no longer matches the client's token in the cookie they send with every AJAX request.
https://developer.wordpress.org/reference/functions/wp_get_session_token/
