### ISSUE TITLE
Feature request: Restrict Google login to specific domain

### ISSUE THREAD

**Issue by ichiefboz** [uhm-coe/authorizer#12]
Could you add a feature to set the `hd` (hosted domain) parameter of the Google logins? I need to be able to force sign-in to be on my college's domain, but I can't use LDAP because this WordPress site is not run by the college itself (I and a bunch of other students run it).

**Comment by figureone** [comment]
Yeah that sounds like a great idea. Can you point me to the google documentation for the parameter?

**Comment by ichiefboz** [comment]
Sure! https://developers.google.com/identity/protocols/OpenIDConnect#authenticationuriparameters (`hd` is at the bottom, there's a lot of other useful ones in that table)

Here's how Google describes it:

> The `hd` (hosted domain) parameter streamlines the login process for Google Apps hosted accounts. By including the domain of the user (for example, `mycollege.edu`), you restrict sign-in to accounts at that domain. For Google Apps customers that have SAML set up with their own authentication infrastructure, the `hd` parameter automatically redirects to that user's SAML resource to log in.
> 
> To protect against client-side request modification, be sure to validate that the returned ID token has a matching `hd` claim (which is proof the account does belong to the hosted domain).

So basically you just have to stick it on as a part of the authentication URI that is used when the user clicks the sign-in button.

**Comment by figureone** [comment]
Awesome. I'll try to get that feature added in to the upcoming release.

**Comment by ichiefboz** [comment]
Awesome, thanks!

**Comment by figureone** [comment]
Can you confirm the version of php that you're using? Google devs added the hd param to google-api-php-client in version 2, but version 2 is only compatible with php 5.4+. For example, ubuntu 12.04 still uses php 5.3.

https://github.com/google/google-api-php-client/issues/321
https://github.com/google/google-api-php-client/blob/master/UPGRADING.md#php-54-is-now-the-minimum-supported-php-version

**Comment by ichiefboz** [comment]
Hey - sorry it's taken me forever to respond. The old server we used to use was on 5.3 and we are upgrading over the summer to 5.6.

**Comment by figureone** [comment]
Aloha, I've integrated the hd param into the codebase, it will make it into the next release. Feel free to check out the master branch if you want to test it out.
https://github.com/uhm-coe/authorizer/commit/e2bf978af50703cf4a90c85f3c8194d427425fa9

Note that we're sticking with v1 of the google-api-php-client for now (since we're still supporting PHP 5.3 shipped with Ubuntu 12.04 LTS); once enough of the install base has migrated to PHP 5.6 or higher, we can upgrade the Google library to v2, and this should work a bit better.

**Comment by figureone** [comment]
New version is out with this feature. Please let me know if you find any problems.
https://wordpress.org/plugins/authorizer/changelog/
