### ISSUE TITLE
WordPress lost password form redirects

### ISSUE THREAD

**Issue by anilnatha** [uhm-coe/authorizer#121]
Hello again! I found an issue with the WordPress "lost your password" feature when Authorizer is installed and could use your guidance on how I may fix it.

When a user bypasses our default login and visits our WordPress login page by appending the query string `external=wordpress`, they can then access the "lost your password" feature. After submitting the 'lost your password' form, the user is redirected to a success view on `wp-login.php` with the query string `?checkemail=confirm&external=cas`. Because Authorizer attempted to send them to our default login page which is CAS by setting `external=cas`, it causes the success page to break:

![image](https://user-images.githubusercontent.com/931107/191783641-9be8f32c-e993-458a-baf2-d0d1a09b9ae7.png)

If I change `external=cas` to `external=wordpress` the page renders correctly and this is where the user should have been sent after submitting the form since they had originally bypassed the default login:

![image](https://user-images.githubusercontent.com/931107/191783859-f5c5fea2-163d-454b-a9ff-8a0ddf3ad105.png)

Any ideas on how this may be remedied?

BTW, Thanks again for all your support on getting the proxy updates added, it's been working great for us.

**Comment by pkarjala** [comment]
Hi, thanks for this report!  This is definitely a workflow issue that should be redirecting to the WordPress login page if you are using `external=wordpress` to access the base WordPress login page.  We'll work on implementing a solution for this!

**Comment by pkarjala** [comment]
HI @anilnatha Can you please confirm the exact settings that you currently have on the Advanced tab of your Authorizer Settings page?  A screenshot would suffice.

Additionally, do you currently have `CAS automatic login` checked under the External Service tab in Authorizer?

**Comment by anilnatha** [comment]
Hi @pkarjala 

Here is a screenshot of the the advanced settings:

<img width="1101" alt="Screen Shot 2022-09-27 at 08 39 12" src="https://user-images.githubusercontent.com/931107/192571747-5173724a-4ddf-4354-a5b1-7c7b9c09f9ff.png">

> Additionally, do you currently have CAS automatic login checked under the External Service tab in Authorizer?

Yes, it is enabled.

**Comment by pkarjala** [comment]
Hi @anilnatha I've just pushed up a code fix to address this issue.  The fix will be included in the next Authorizer release!. 
 Thank you again for the report!

**Comment by anilnatha** [comment]
Thank you for addressing the issue @pkarjala and @figureone! I'll update our instance and report back if I encounter any issues.
