### ISSUE TITLE
OAuth2 Documentation

### ISSUE THREAD

**Issue by ianchan** [uhm-coe/authorizer#123]
Hi,

This plugin is wonderful and perfect for our needs. Thank you for providing it. 

Would it be possible to include some documentation on the OAuth2 option and include with the list of what is available on the plugin home page?

**Comment by figureone** [comment]
Good idea, it's been a long time since we've updated the plugin home page and readme. Thanks, I'll keep this thread open until we have some changes to report!

**Comment by figureone** [comment]
Aloha, we made some minor updates to the OAuth2 documentation in version 3.6.1.

Also, there are inline instructions on the **Help** tab (upper right corner) when viewing the Authorizer Settings page on the WordPress Dashboard. The section on External Service has the OAuth2 details.

If you get a chance, please review and let us know if you suggest any edits. Thanks!
