### ISSUE TITLE
Make STARTTLS LDAP option more precise on UI

### ISSUE THREAD

**Issue by TuringTux** [uhm-coe/authorizer#129]
Currently, the checkbox "Use TLS" enables STARTTLS:

https://github.com/uhm-coe/authorizer/blob/05bcdc6921478154232240fb52a464a34f172cd1/src/authorizer/options/external/class-ldap.php#L104

If the user specifies an `ldaps://` connection, the checkbox has no effect:

https://github.com/uhm-coe/authorizer/blob/05bcdc6921478154232240fb52a464a34f172cd1/src/authorizer/class-authentication.php#L1105

In my opinion, the UI is not quite clear regarding these things. I would therefore propose the following changes:

* Replace "Use TLS" with "Use STARTTLS" (because TLS is also used in an `ldaps://` connection)
* Replace "If ldaps is used, this should be unchecked" with "If ldaps is used, this has no effect" (to be more explicit)

If you want, I can try to open a PR with these particular changes.

**Comment by figureone** [comment]
Both those changes look reasonable, thanks! We'll get that added to the next version. Pull request would definitely be appreciated

**Comment by TuringTux** [comment]
I'll give it a shot as soon as I find the time (probably only in one or two weeks).

**Comment by TuringTux** [comment]
Done! #132 now contains the proposed changes (and attempts to localize them to Spanish and French, however, I am not too certain about them being correct).
