### ISSUE TITLE
Redirect loop for CAS Login

### ISSUE THREAD

**Issue by StevieDrew** [uhm-coe/authorizer#135]
Hi! I'm using Wordpress 6.3.2 and have just set up the Authorizer plugin. It's configured for a CAS 3.0 client server. I'm able to authenticate on my 3rd party page, but I then get stuck in a redirect loop that doesn't allow me to return to the Wordpress dashboard. Not sure if this may be a cookie issue?

**Comment by pkarjala** [comment]
Consolidating discussion to #134; will reference there.
