### ISSUE TITLE
error to connect ldap

### ISSUE THREAD

**Issue by lagethomas** [uhm-coe/authorizer#137]
Estou testando o plugin, mas quando aprovo um usuário que tentou fazer login, ele não cria o usuário no banco de dados wordpress e o login não acontece.
Estou usando o ldap.

**Comment by figureone** [comment]
You can also use the LDAP Test to get debug information about where it might be failing:
<img width="717" alt="Screenshot 2023-11-30 at 1 10 15 PM" src="https://github.com/uhm-coe/authorizer/assets/125274/ab916fa4-9782-4ad2-8195-3587acacf96c">

**Comment by figureone** [comment]
If you want to avoid manually approving users you can set "Who can log into this site?" to "All authenticated users" and then configure your LDAP Search Filter to be the specific AD group(s) you want to allow. Note that the WordPress accounts are only created when the user logs in.

You can set "LDAP attribute containing email address," "LDAP attribute containing first name," and "LDAP attribute containing last name" to map those values to the WordPress account. If you have a custom usermeta field for phone number, you can hook into `authorizer_additional_ldap_attributes_to_retrieve` to specify the LDAP attribute, and then hook into`authorizer_allow_login` to fetch that value when a user logs in and call `update_user_meta()` to save the attribute to the WordPress account.
See this pull request for details: https://github.com/uhm-coe/authorizer/pull/94

**Comment by lagethomas** [comment]
> @pkarjalae@figureone
> 
> Bom Dia pessoal. Desculpe a demora. O Plugin funciona, valida a autenticação e aparece para eu aprovar a entrada do usuário no site certo. O problema é que depois que eu aprovo o usuário não é criado no banco de dados Wordpress e mesmo depois de aprovar ele não efetua login. Ele pede novamente para conceder acesso. Foi possível criar o usuário utilizando o miniOrange, mas como ele é pago a maioria dos recursos não funciona. Tenho que usar "Authorizer" junto com "miniOrange" para fazer uma autenticação mais "completa". Eu aprovo através do Autorizador e quando uma pessoa faz login após a aprovação, o miniOrange cria o usuário e as informações são mapeadas pelo Autorizador. Foi meio que um truque, mas está funcionando. Seria bom poder fazer tudo através do Autorizador.
> 
> * Aprovar o usuário
> * Criar usuário sem login (importado do LDAP)
> * Mapeie os campos (Nome, Email, telefone)
> * Filtre um grupo específico do Active Directory sem precisar trazer o diretório inteiro
> * Aprovação automática (Assim, ao constatar que o usuário existe no grupo AD, ele aprova e cria automaticamente o usuário no banco de dados Wordpress)

In this case, even though the user exists and approval takes place, the user is not created.

**Comment by lagethomas** [comment]
When I apply the filter it says it can't find the user

![image](https://github.com/uhm-coe/authorizer/assets/47001888/d6ebba70-d265-496a-997f-4d5a99ab41eb)

**Comment by lagethomas** [comment]
I managed to make it work!  In principle everything is fine, the basic attributes.

**Comment by pkarjala** [comment]
If you don't mind sharing what the solution was to help others, that would be great!

Marking resolved.

**Comment by lagethomas** [comment]
> If you don't mind sharing what the solution was to help others, that would be great!
> 
> Marking resolved.
This is the configuration in my Wordpress
LDAP Host  =  IP_SERVER
LDAP Port = PORT_SERVER
LDAP Search Base = dc=your,dc=domain,dc=local
LDAP Search Filter = (memberOf=CN=INTRANET_LOGIN,OU=GROUPS,OU=03 - OTHERS,DC=your,DC=domain,DC=local) - Filter with group of Active Directory
LDAP attibute containing username = sAMAccountName
LDAP attibute containing email address = @valgroupco.com
LDAP Directory User = CN=Services Account,CN=Users,DC=your,DC=domain,DC=local
User with permission for read your Active directory
LDAP Directory User Password = YOUR_PASSOWRD_USER_AD
LDAP attribute containing first name = givenName
LDAP attribute containing last name = sn
LDAP attribute update = Update firt and last name fields on login (Choose according to your option)
