### ISSUE TITLE
Allow multiple configured CAS/LDAP/Google endpoints

### ISSUE THREAD

**Issue by figureone** [uhm-coe/authorizer#14]
Several requests point to allowing any number of CAS/LDAP/Google endpoints being configured:
- Scott at capilanou.ca has 2 LDAP search bases (ou=students, ou=faculty) that he wants to authenticate against. We could adjust the ldap_search() filters, or just allow multiple LDAP endpoints to be defined.
- tkilcommons requests 2 Google Apps domains (sub.uni.ac.uk and uni.ac.uk). Note that multiple Google endpoints will result in multiple Google login buttons.
  https://wordpress.org/support/topic/two-approved-google-apps-domains/
- jwillis84 requests 2 CAS endpoints. Note that multiple CAS endpoints will result in multiple CAS buttons.
  https://wordpress.org/support/topic/support-for-alternate-cas-sources-cas1-or-cas2-by-user/#post-8174505

**Comment by gallandarakhneorg** [comment]
I vote for CAS configurations on multiple CAS servers. I need to use 2 CAS servers from partners institutions to be connected on a shared WP site.

**Comment by figureone** [comment]
Better late than never...configuring multiple CAS servers should land in the next version. 

LDAP config already allows specifying multiple servers. So that leaves multiple endpoints for Google and Oauth2 not implemented. We'll close this issue for now but if there is interest in those we can reopen.
