### ISSUE TITLE
composer install : 404 error for the sabinus52/multi-select dependency

### ISSUE THREAD

**Issue by julienlusson** [uhm-coe/authorizer#146]
Hi @figureone

The project sabinus52/multi-select was removed from github : https://github.com/sabinus52/multi-select

It cause problems when installing WordPress with composer, for example with Bedrock : https://github.com/roots/bedrock

Can you create a fork in https://github.com/uhm-coe with your version of the module?

I've also seen this (old) version : https://github.com/lou/multi-select

Thanks!

**Comment by figureone** [comment]
Thanks for catching that! We removed the composer package and replaced with the copy from the original developer.
https://github.com/uhm-coe/authorizer/commit/9745d2e4bb7c54cf7a6a978d6c70feb84480ff0c

Version 3.7.1 is now out with the change.
