### ISSUE TITLE
OAuth2 Add Custom

### ISSUE THREAD

**Issue by nuozxy** [uhm-coe/authorizer#148]
Can OAuth2 login be customized like Wiki.js to obtain username and password information on the OAuth2 server.
![{E3AE89D2-61E2-4ed0-A0D0-0619B60C1AEC}](https://github.com/uhm-coe/authorizer/assets/83659430/0aa2459b-75cb-48df-8b2e-205105b3ad60)

**Comment by figureone** [comment]
We'll look into it! We're using a few different oauth2 backends (azure, github, generic), so it might be a bit different for each of them. Which specific one are you using?

**Comment by nuozxy** [comment]
Support configuring the field name of the username in the user information returned by the backend user information interface

**Comment by nuozxy** [comment]
![Uploading 6fe3d9bfac2826a8fbaaa178f20235f1.png…]()

**Comment by nuozxy** [comment]
![Uploading 6fe3d9bfac2826a8fbaaa178f20235f1.png…]()

**Comment by nuozxy** [comment]
![6fe3d9bfac2826a8fbaaa178f20235f1](https://github.com/uhm-coe/authorizer/assets/83659430/40bb96b6-c8f8-409b-b677-b774ba63fc67)

**Comment by figureone** [comment]
FYI, the upcoming version of Authorizer will include new fields for specifying username, email, first name, and last name for the OAuth2 (generic) provider:
![Screenshot 2024-09-24 at 2 56 47 PM](https://github.com/user-attachments/assets/8878964f-6b14-4181-a070-59734955b4a2)
