### ISSUE TITLE
When closing the Sign In with Google popout, modal hangs

### ISSUE THREAD

**Issue by pkarjala** [uhm-coe/authorizer#15]
When Sign in with Google is enabled, click on the button to sign in, then immediately close the new authentication window.

This causes the spinner overlay to block access to the page elements, and the page must be reloaded to access any options.

Desired behavior should be that the spinner overlay is removed and the page is accessible again without a reload.

**Comment by figureone** [comment]
Fixed in https://github.com/uhm-coe/authorizer/commit/3d8c38d756c3c9769ceda9ad421b98ccd4645313
