### ISSUE TITLE
Unable to write the text in "What message should pending users see after attempting to log in?"

### ISSUE THREAD

**Issue by dorianborovina** [uhm-coe/authorizer#152]
Hello everyone,

First thing's first, great job with the plugin! So far, it looks and works amazing!

The issue I'm having is quite simple.

I just can't fill out the text in fields such as "What message should pending users see after attempting to log in?", "What message should blocked users see after attempting to log in?" or in "Welcome email body".

I can see the text fields, but clicking on them, or typing text does nothing.

![image](https://github.com/uhm-coe/authorizer/assets/24650319/e600be29-ed82-458a-8583-e585b68843d3)

I'm using the WP 6.5.4 on Debian 12, PHP 8.2.18, Nginx and the WP-Optimize plugin (Tried disabling it too).

Any ideas?

Thanks in advance,
Dorian

**Comment by dorianborovina** [comment]
Hmm, maybe this gives you an idea?

![image](https://github.com/uhm-coe/authorizer/assets/24650319/e41bdcf4-ce54-45f4-9081-095f44344d04)

**Comment by pkarjala** [comment]
Hi @dorianborovina can you please confirm which version of Authorizer you have installed?

We have had reports of this issue before but haven't been able to narrow it down to a specific cause; the browser JS console logs and the nginx logs may point at something specific we can dig into further once we know which version of Authorizer you're on.

Thanks!

**Comment by dorianborovina** [comment]
Hi Patrick,

I have the latest one I guess, the v3.8.3

Thanks,
Dorian

**Comment by pkarjala** [comment]
Thanks; do you have any other plugins besides WP-Optimize installed and enabled?

**Comment by dorianborovina** [comment]
Not really no, I remember I deactivated all of them as a part of the
troubleshooting.

But that was a while ago, I'll try again when I catch some air. :)

**Comment by pkarjala** [comment]
OK, no problem; we can still start troubleshooting from here!

**Comment by figureone** [comment]
Thanks for helping track down this longstanding issue! We narrowed it down to some javascript that moved the TinyMCE editor fields in the DOM (to support animating the hide/show effect for those fields).

The fix will be included in the next release of Authorizer, but you can see the changes here and apply the hotfix if you want to get it fixed sooner: https://github.com/uhm-coe/authorizer/commit/17c897b70dce1c601a76db3063308c0411d84864
