### ISSUE TITLE
How to set the scope in the authorizer plugin

### ISSUE THREAD

**Issue by toywl** [uhm-coe/authorizer#154]
How to set the scope in the authorizer plugin
![image](https://github.com/user-attachments/assets/b2362124-b2b1-4cef-aa29-4fcb649e386d)

**Comment by figureone** [comment]
You should be able to hook `authorizer_oauth2_generic_authorization_parameters` to set the scope, let us know if you run into problems:
https://github.com/uhm-coe/authorizer/issues/142#issuecomment-1981620112
