### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS With CAS

### ISSUE THREAD

**Issue by wixaw** [uhm-coe/authorizer#163]
Hello
I have "ERR_TOO_MANY_REDIRECTS" every time I make a new connection with CAS 3 ( apereo)  and 2 seconds later it redirects to the site, any idea?"

![image](https://github.com/user-attachments/assets/18b5d4b8-fc5e-4743-9ca2-25cf71467fa4)
Thanks

**Comment by figureone** [comment]
Weird. I'm not as familiar with the handshake process in the older CAS protocols, have you tried switching to one of the newer protocols and seeing if the behavior changes? Hard to say what the CAS server you are using supports.
<img width="338" alt="Screenshot 2024-09-11 at 9 36 10 AM" src="https://github.com/user-attachments/assets/a05fd3a9-4439-4944-a51f-cdaaae916860">

**Comment by wixaw** [comment]
Sorry, I was wrong, I did set CAS 3.0

**Comment by wixaw** [comment]
Well, in reality, the problem did seem to come from that. Indeed, I had a difference between my production site and the development one; one was on 2.0 and the other on 3.0. And with the 'CAS behind a proxy' option, it seems that the problem is no longer there and the initial connections are faster!
Thank you very much for the lead.
