### ISSUE TITLE
HTTP redirect status code must be a redirection code, 3xx.

### ISSUE THREAD

**Issue by aitor-alvarez** [uhm-coe/authorizer#167]
Hi there,

I am getting the above mentioned error when the option "hide WP logins" is selected. 

This option can be found under "advanced settings" (see the image below). 
Before today, when this option was checked, it would redirect automatically to the CAS url when visiting /wp-login.php Now, after the last update (Version: 3.10.1), the "HTTP redirect status code must be a redirection code, 3xx." error appears if this option is enabled. 

![Screenshot 2024-09-25 205525](https://github.com/user-attachments/assets/076221a2-8fe1-4f59-9027-d3a16e9bfdcd)

Thanks

**Comment by WorksAtAUni** [comment]
Seeing same... multiple sites, CAS shop.

**Comment by greg-randall** [comment]
I put in a [pull request](https://github.com/uhm-coe/authorizer/pull/168) with a fix.

**Comment by BLLuten** [comment]
This one caught me.  `/wp-login.php?external=wordpress` along with my password manager to the rescue.

**Comment by figureone** [comment]
Ugh yeah, sorry! Also remember you can use the password reset email if you happen to not know your WordPress user password. (Unless you have Authorizer configured to disable WordPress logins completely! Then you're stuck with editing the database to turn that flag off, or disable Authorizer.)
