### ISSUE TITLE
Multiple Site Subscription 

### ISSUE THREAD

**Issue by CountryNerd** [uhm-coe/authorizer#22]
In MU. If I have a user login into a child site. Can I have them also be enrolled into an additional site at the same time?

Example: User logins into sites.ewu.edu/appdev/
I would like them to be also added to site.ewu.edu/

This might not be doable but it's a feature that might be nice.

**Comment by pkarjala** [comment]
@CountryNerd In this scenario, are you talking about only registering the user with the Network site, or are you also talking about registering the user with other sub sites, such as `sites.ewu.edu/appdev2/`?

**Comment by pkarjala** [comment]
Hi @CountryNerd following up to see if you can still offer clarification.  Thanks!

**Comment by pkarjala** [comment]
Due to no response in 4 months, marking this issue closed.  Please re-open it if you would like to resume discussion.
