### ISSUE TITLE
case sensitive LDAP attributes

### ISSUE THREAD

**Issue by yatesconsulting** [uhm-coe/authorizer#27]
Thanks for the great plugin, and commitment to updates.

I am using LDAP against Active Directory, and found these two fields seem to be case sensitive, which I believe is incorrect.

LDAP attribute containing first name: givenname works, but givenName doesn't work
LDAP attribute containing email: userprincipalname works, but userPrincipalName doesn't work

**Comment by figureone** [comment]
The php-ldap module converts every attribute retrieved from LDAP to lowercase:
http://php.net/manual/en/function.ldap-get-entries.php#107267

I'll add code to lowercase anything written in the Authorizer Settings fields, so you can type in whatever case you'd like.
