### ISSUE TITLE
email defaulting incorrectly when DC=..,DC=...,DC=...

### ISSUE THREAD

**Issue by yatesconsulting** [uhm-coe/authorizer#28]
When the userprincipalname fails to populate the email address, the email seems to be created by adding the  username, @, and last two DC values in LDAP Search Base.  While this might not be a bad guess for most, our LDAP strings end with DC=risd,DC=k12,DC=nm,DC=us .  Please consider this guess to include all DC values, regardless of number.  This is a pretty minor issue, and probably doesn't affect many people, so if it's a hard fix, I would just note the limitation.
Thanks,
-Bryan

**Comment by yatesconsulting** [comment]
Ok, so NOW I find the year old thread on this topic at https://wordpress.org/support/topic/ldap-auth-not-working/ .  I found it to still behave as described above, and in the support thread.  I was doing this while using the "LDAP attribute containing email" of userPrincipalName.  When using userprincipalname, it pulls correctly from AD.  Hope this helps.

**Comment by figureone** [comment]
Case sensitivity issue fixed in #27, and will be included in the next release. Thanks!
