### ISSUE TITLE
CAS Login by Username

### ISSUE THREAD

**Issue by jwnoble** [uhm-coe/authorizer#3]
Hello - This is a great WP plugin thanks. Our CAS authorizes by username and not email address. Is there a way to change that in the plugin?  Thanks!

**Comment by figureone** [comment]
Authorizer won't change they way your users do CAS logins, so they can still log in with their username (not email address). However, every WordPress account must have an email address, so you need to fill out "CAS attribute containing email" to associate that CAS login with its WordPress account.

**Comment by jwnoble** [comment]
Thank you... that works!

**Comment by figureone** [comment]
Great!
