### ISSUE TITLE
Implement paging on approved list

### ISSUE THREAD

**Issue by figureone** [uhm-coe/authorizer#31]
Having lots (1000+) of users in the approved list will slow page load times and run up against PHP limits on the number of form elements allowed on a page. Implement paged user lists.

Ideally, should be able to sort by date added, user role, or alphabetically by email. Also would like to filter the list by a search term.

**Comment by figureone** [comment]
Related threads:
https://wordpress.org/support/topic/slow-performance-with-lots-of-users/
https://wordpress.org/support/topic/dashboard-widget-cant-load-large-number-of-users-2/

**Comment by figureone** [comment]
Related
https://wordpress.org/support/topic/access-list-tab-too-slow/

**Comment by figureone** [comment]
This feature will be included in the next release.
https://github.com/uhm-coe/authorizer/commit/25c2e17beceff634c5781ffaba77883616b176d6 https://github.com/uhm-coe/authorizer/commit/d4111e043c3b72234eb04230e88d1353b18d5d86 https://github.com/uhm-coe/authorizer/commit/8360d02c351b42248f4bf61690516fa111240018 https://github.com/uhm-coe/authorizer/commit/2727a475c954275a2ba0c5aa8ff5168e85fd4478 https://github.com/uhm-coe/authorizer/commit/4dbbdcf97e1649c1735064c854bf2634c719e319

**Comment by pkarjala** [comment]
Feature is now live in Authorizer 2.7.0.
