### ISSUE TITLE
Generic OAuth2 logins possible?

### ISSUE THREAD

**Issue by poVoq** [uhm-coe/authorizer#32]
From a quick glance at the code this plug-in it seems the Google auth is using OAuth2? Is there something that would prevent duplicating the Google vendor and modifying it to allow to authenticate against other OAuth2 supporting services?

In my specific case I would like to authenticate against a Oauth2 supporting Nextcloud12 instance and this plugin seems to provide really nice functionality for something like that.

I am not an expert on this kind of authentication systems, so a quick feedback in the sense of "yeah, should work without too much effort" would be really appreciated before I try to wrap my head around the specific code. Thanks!

**Comment by figureone** [comment]
I'd like to get this on the roadmap, it sounds like a good idea. We run owncloud (and are evaluating nextcloud) over here, and both are currently tied to LDAP for authentication; I could see us switching to OAuth at some point for added security benefits (2FA, individual app authorizations, etc.).

Regarding the plugin, Google authentication is done using Google's codebase:
https://github.com/google/google-api-php-client/tree/v1-master
https://github.com/uhm-coe/authorizer/blob/master/authorizer.php#L1023-L1025

So we aren't directly implementing OAuth2 yet. I haven't done any research yet to see if there are any good PHP libraries to do the OAuth flow (and whether they could be used to replace the Google library, or whether they would both have to be included).

**Comment by poVoq** [comment]
I see, so definitely out of my league then :(

But I am also looking into doing the same with my DokuWiki and there is a plug-in that seems to do this (see: https://www.dokuwiki.org/plugin:oauth ), and uses the following php lib:
https://github.com/Lusitanian/PHPoAuthLib
No idea if that one is good or bad, but it seems to fit the description.

**Comment by poVoq** [comment]
I see, so definitely out of my league then :(

But I am also looking into doing the same with my DokuWiki and there is a plug-in that seems to do this (see: https://www.dokuwiki.org/plugin:oauth ), and uses the following php lib:
https://github.com/Lusitanian/PHPoAuthLib
No idea if that one is good or bad, but it seems to fit the description.

Edit: Details of the OAuth2 provider implementation for Nextcloud are here: https://github.com/soudis/oauth2

**Comment by figureone** [comment]
Also received a request for Kerberos integration:
https://wordpress.org/support/topic/sso-5/

Adding that to the feature request here.

**Comment by figureone** [comment]
Also a request for Synology SSO: https://global.download.synology.com/download/Document/DeveloperGuide/Synology_SSO_API_Guide.pdf

**Comment by figureone** [comment]
Added OAuth2 support in version 3.0:
https://github.com/uhm-coe/authorizer/commit/92161f06a789614680b1e0fb869294303f1140da
