### ISSUE TITLE
Role wrongly set

### ISSUE THREAD

**Issue by ocager** [uhm-coe/authorizer#34]
Hello,

since a while (I cannot exactly say since when), I have an issue with the role set to the user who is logging in via the plugin. We are using CAS.

- In Authorizer, Tab "External Service", I set "Author" as default role for new users.
- When I logon as non-registered user (in WordPress), the new user is correctly created, but with the role "Editor".
- When I logon as already-registered user (in WordPress), it is overwriting my defined role ("Subscriber") with the role "Editor" (so I´m losing my role assignment for each user who is logging in).
- I´ve just changed the default role for new users to "Subscriber" and checked again, but new and already known user's role is set to "Editor".

I´ve invested the whole day in bugfixing and installed it in a fresh installed WordPress environment, but I have the same behavior.

Hope someone can help me!

Thanks.

**Comment by figureone** [comment]
Are you using any external services (LDAP, CAS, or Google)? Or are you using the built-in registration system? If you have "Anyone can register" set in options-general.php, the New User Default Role there will take precedence. Authorizer default role is only for new users coming from external services.

**Comment by ocager** [comment]
Hi Paul, thanks for answering.
1. We are using CAS (see screenshot)
2. The _Anyone can register_ function is disabled.
3. Regarding your last sentence. I don´t know why, but I have an existing user and gave me multiple roles in WordPress. But everytime when I´m logging in via CAS, my role is resetted to the _Reader_ role. So it might be that I`m not recognized as known user? Because it´s taking the role set in field _New User Default Role_ in Options/General. We are using the mail address as username. Is there a logfile that I can provide which might help to find the reason for this behavior?

Thank you so much!

![snap 2017-08-03 at 07 18 48](https://user-images.githubusercontent.com/30630832/28907027-2dd8089c-781c-11e7-944f-6ddf073e0109.png)

![snap 2017-08-03 at 07 21 09](https://user-images.githubusercontent.com/30630832/28907043-598182ac-781c-11e7-997b-3a27b76e0983.png)

**Comment by figureone** [comment]
Ok thanks! Looking into it, will let you know if I need more details.

**Comment by pkarjala** [comment]
Hi @ocager what is the currently set option under Authorizer -> Login Access -> Who can log into the site?

**Comment by ocager** [comment]
Hi Patrick, all authenticated users can login, please find the screenshot below.
Regards

![snap 2017-08-10 at 07 18 53](https://user-images.githubusercontent.com/30630832/29155433-4be36270-7d9c-11e7-963a-04424a7eb594.png)

**Comment by pkarjala** [comment]
Thanks for the confirmation.  Can you also verify the following:

- The version of WordPress
- The version of Authorizer
- Theme being used in WordPress
- Any other installed Plugins

**Comment by ocager** [comment]
Hi Patrick,
your questions were the basis to create a clean WP installation including the plugins I´m using. Finally, it seems that the plugin "Multiple User Role" is the reason for the role reset after each user login. With deactivation, the user role remains as it is. I´m a little bit sad because I need the function of the plugin, because we have a developed role concept which requires multiple role assignments for users. Now, I have to think about a new concept.
However, the problem is not based in Authorizer (I would summarize), it´s the combination with the above mentioned plugin.
Paul, Patrick, thank you very much for your support!

**Comment by pkarjala** [comment]
Thank you for the follow up!  I'm sorry to hear that the other plugin was causing the issue; we did have a brief discussion regarding multiple user roles support going on at https://wordpress.org/support/topic/multiple-role-support/ but it is not currently supported by Authorizer.

**Comment by ocager** [comment]
Thanks for the update.

One further question (or should I open a new issue?). I´m receiving in the Dashboard of WP Admin *sometimes* the message "_Can't reach CAS server. Please provide accurate CAS settings if you intend to use it._".

However, the login function is working well. Is there a logfile or anything else to investigate what´s the reason for the message?

![snap 2017-08-10 at 23 46 22](https://user-images.githubusercontent.com/30630832/29193602-65b0c104-7e26-11e7-9265-de42fee071a6.png)

**Comment by pkarjala** [comment]
Hi @ocager , please open a separate issue regarding this item.  Thanks!
