### ISSUE TITLE
Message "Can't reach CAS server. Please provide accurate CAS settings if you intend to use it." appears sometimes

### ISSUE THREAD

**Issue by ocager** [uhm-coe/authorizer#35]
I´m receiving in the Dashboard of WP Admin **_sometimes_** the message "Can't reach CAS server. Please provide accurate CAS settings if you intend to use it.".

However, the login function is working well, so I assume that the connection is existing. Is there a logfile or anything else to investigate what´s the reason for the message? (because it appears to any user accessing WP Admin).

![snap 2017-08-10 at 23 46 22](https://user-images.githubusercontent.com/30630832/29198003-87fb0138-7e40-11e7-9bdf-95862458e5a8.png)

**Comment by pkarjala** [comment]
Hi @ocager there are a few reasons why this message may occur.

The function is at https://github.com/uhm-coe/authorizer/blob/master/authorizer.php#L2201 and will attempt to connect to your CAS server via either port 80, 8080, or 443 (http or https).  If it cannot reach the server on these ports, or the port defined in the CAS settings under the External Service tab in Authorizer, it will throw the message error.

The other cause can be if the server's response is NOT a 200 type response; if there is any redirect or 404 response, it will throw this message error.

Finally, we have run into a strange edge case where if the time settings on the server are not accurate, the message will appear.  This can be fixed by making sure your server is correctly communicating with a NTP server and has correctly set its local time and timezone.

Hope this helps!

**Comment by ocager** [comment]
Hi Patrick,

maybe I didn´t described the behavior detailed enough. The message appears also if I´m already logged in and I just navigate to www.site.com/wp-admin.

I checked the 1st and 3rd point with our infrastructure guys and here, it should be all okay. Regarding the second point, I do not really know how I shall evaluate if I´m receiving a 200 type response or not. As described previously, I´m already logged in and if I´m in WP Admin and looking on the console, I can´t find a 404 response or anything else, but I find also no SSO URL (as I´m already logged in). Is there another way to find it out?

Otherwise, as I don´t hear from over 200 users any issues about the CAS login, I´m just planning to hide this message (as it appears to every user in WP Admin).

Thank you for your support!

**Comment by pkarjala** [comment]
Thank you, the original description you provided is fine.

You can check the response from the query Authorizer sends by adding a quick line of testing code to https://github.com/uhm-coe/authorizer/blob/master/authorizer.php#L5856 which is the function that does the remote connection check.

On line 5860, try adding:

`error_log( "Response information from server: ", 0 );
error_log( print_r( $response, true ), 0 );
error_log( print_r( $response_code, true ), 0 );`

This will output the server response to the logging service for PHP on your server.  Depending on your configuration, this will either be output to PHP error log or the web server's (such as Apache) error log.

Hope this helps!

**Comment by ocager** [comment]
Hi Patrick,
thanks for your kind explanation. I did it and found the following message in the logfile. I think the interesting notice is **_cURL error 28: Resolving timed out after 5515 milliseconds_**. Do you have an assumption what´s the problem?

_[Thu Aug 17 10:53:03.680367 2017] [php7:notice] [pid 26114] [client 10.11.0.47:64291] Response information from server: , referer: http://www.site.local/
[Thu Aug 17 10:53:03.680401 2017] [php7:notice] [pid 26114] [client 10.11.0.47:64291] WP_Error Object\n(\n    [errors] => Array\n        (\n            
[http_request_failed] => Array\n                (\n                    [0] => **cURL error 28: Resolving timed out after 5515 milliseconds**\n                
)\n\n        )\n\n    [error_data] => Array\n        (\n        )\n\n)\n, referer: http://www.site.local/
[Thu Aug 17 10:53:03.680405 2017] [php7:notice] [pid 26114] [client 10.11.0.47:64291] , referer: http://www.site.local/_

**Comment by pkarjala** [comment]
At this point you would need to troubleshoot the connection between the server hosting the WordPress instance and your CAS server.  The default timeout for `wp_remote_get` is 5 seconds (as per https://codex.wordpress.org/Function_Reference/wp_remote_get).  One option would be to try increasing the timeout on line 5858 as per the function reference above.

```
$args = array( 'timeout'     => 10 );
$response = wp_remote_get( $url, $args );
```

**Comment by ocager** [comment]
Patrick, thank you very much. I will follow up this topic with our infrastructure guys and keep you posted about the final result. However, as it seems to be more a network issue, I close this topic.
One final question: Is there a possibility to "Buy you a beer" via PayPal? I would like to thank you for your quick and target-oriented support.

**Comment by pkarjala** [comment]
Hi @ocager Glad to be able to help!

Our work on this plugin is done with the support of the College of Education at the University of Hawaiʻi at Mānoa; it's actually part of my day job.  If you would like to support us, please consider making a donation at https://giving.uhfoundation.org/give-now?school_code=EDUC by selecting the "College of Education General Endowment Fund" option.

**Comment by ocager** [comment]
OK, I just did it. Thanks again!
