### ISSUE TITLE
Unable to login since update to v2.6.20 (patch included)

### ISSUE THREAD

**Issue by boris-lechner** [uhm-coe/authorizer#38]
Hi,

since update to v2.6.20, we were unable to login.
In log files, I've found this line :
`PHP Warning:  Invalid argument supplied for foreach() in (...)/www/wp-content/plugins/authorizer/authorizer.php on line 1215`

The problem is with these lines :
```php
// Each of the emails in the array needs to be set to lowercase.
$externally_authenticated_email = array();
foreach ( $cas_attributes[$auth_settings['cas_attr_email']] as $external_email ) {
	$externally_authenticated_email[] = mb_strtolower( $external_email );
}
```

Here, the content of `$cas_attributes[$auth_settings['cas_attr_email']]` isn't an array.

So here is my workaround :
```php
// Each of the emails in the array needs to be set to lowercase.
$externally_authenticated_email = array();

if ( is_array($cas_attributes[$auth_settings['cas_attr_email']]) ) {
	$external_emails = $cas_attributes[$auth_settings['cas_attr_email']];
} else {
	$external_emails = array($cas_attributes[$auth_settings['cas_attr_email']]);
}
foreach ( $external_emails as $external_email ) {
	$externally_authenticated_email[] = mb_strtolower( $external_email );
}
```

Regards

**Comment by figureone** [comment]
Thanks, sorry about that, it was a regression in the last version. It should be fixed in version 2.6.21 now, please let us know if you have problems!
https://github.com/uhm-coe/authorizer/commit/cbe649e0ad57c3ab437ebe67fe34044822c11af9
@pkarjala
