### ISSUE TITLE
ensuring user has the same role as their approved list entry

### ISSUE THREAD

**Issue by dsusco** [uhm-coe/authorizer#41]
After looking at this bit of code I believe there is a bug here: https://github.com/uhm-coe/authorizer/blob/master/authorizer.php#L860

	// Ensure user has the same role as their entry in the approved list.
	// (This is just a precaution, the role should already be set when
	// saving admin options in the sanitizing function.)
	if ( $user_info && ! array_key_exists( $user_info['role'], $user->roles ) ) {
		$user->set_role( $user_info['role'] );
	}

`array_key_exists` is checking if $user->roles[$user_info['role']] exists. I believe `in_array` should be used here instead.

As it's written right now, this if clause is always executing for me and a user never has more than their default role (I'm assigning multiple roles to a user).

**Comment by pkarjala** [comment]
Thank you for the report; if you are able, can you please submit a pull request for this patch?

**Comment by dsusco** [comment]
Sure. Just the patch? No tests or anything?

**Comment by pkarjala** [comment]
Just the patch; we'll review and test it internally.  Thanks!

**Comment by dsusco** [comment]
All set: #43.

**Comment by figureone** [comment]
Version 2.6.22 released with this fix. Thanks for your help, and again, please open a new issue if you'd like to continue discussion on multiple-role issues. Cheers!
https://github.com/uhm-coe/authorizer/commit/62fedbcb40d7fd8707ac1a283da3e6fab3e471e5

**Comment by dsusco** [comment]
Thanks. Shouldn't be an issue here as the if condition won't evaluate to true in our sites.
