### ISSUE TITLE
Version 2.7.0 doesn't work with php 5.3.3 and 5.4

### ISSUE THREAD

**Issue by klausdk** [uhm-coe/authorizer#47]
Authorizer  gives this error on php 5.3.3 and 5.4 :

PHP Fatal error:  Can't use method return value in write context in .../wp-content/plugins/authorizer/authorizer.php on line 3238

It works with php 5.6

On redhat 6.x php is version 5.3.3 by default and version 5.4 on redhat 7. So there will probably be others with the same problem.

**Comment by figureone** [comment]
Thanks for the report, will get a fix out shortly!

**Comment by figureone** [comment]
Version 2.7.1 has been released: https://wordpress.org/plugins/authorizer/#developers
