### ISSUE TITLE
Update phpCAS functionality to allow for Shibboleth integration

### ISSUE THREAD

**Issue by pkarjala** [uhm-coe/authorizer#50]
See information in discussion at https://wordpress.org/support/topic/using-shib-to-serve-cas/

**Comment by figureone** [comment]
Allowing CAS servers behind redirected URLs:
https://github.com/uhm-coe/authorizer/commit/cc8ba527f362e5e1ac9d52f26465f9e549a686a7

Using serviceValidate endpoint to check CAS server reachability:
https://github.com/uhm-coe/authorizer/commit/9555e0ee99152aa00431de5e0d6780c48ec6c6e8
