### ISSUE TITLE
Add more CAS Attributes?

### ISSUE THREAD

**Issue by pablo-tapia** [uhm-coe/authorizer#52]
I was wondering if there's any way I can add additional attributes when users use CAS for login? So far I only see email, first and last name but I need to add at least 5 or 6 more fields. Is this is possible?

**Comment by figureone** [comment]
As it stands, you could hook into `authorizer_custom_role` and do your usermeta updates there:
https://github.com/uhm-coe/authorizer/blob/master/authorizer.php#L714-L723

For example:
```
function my_authorizer_add_custom_usermeta( $role, $user_data ) {
	if ( isset( $user_data['cas_attributes']['your_cas_attribute'] ) ) {
		$user = get_user_by( 'email', $user_data['email'] );
		if ( false !== $user ) {
			update_user_meta( $user->ID, 'your_meta_key', $user_data['cas_attributes']['your_cas_attribute'] );
		}
	}

	return $role;
}
add_filter( 'authorizer_custom_role', 'my_authorizer_add_custom_usermeta', 10, 2 );
```
