### ISSUE TITLE
Add custom urls for "publicly available pages" - IPN PayPal issue

### ISSUE THREAD

**Issue by mauroits** [uhm-coe/authorizer#55]
Hello, I love this plugin but there is an issue forcing me to unistall it: Authorizer is blocking the IPN listener so I cannot use Paypal in my site.
It would be enough to add a custom field for exception, publicly available urls not in the list.

I would appreciate if you can suggest me a workaround to add my IPN listener url, maybe by coding.
Thank you

**Comment by figureone** [comment]
What does your PayPal IPN URL look like? If it's just a querystring value on your site root URL, then I think you can make your home page public (Authorizer Settings > Public Access > Public Pages) so requests for that URL aren't blocked by Authorizer.

If it's a specific endpoint, we can look into opening that up. We already do something similar for REST endpoints:
https://github.com/uhm-coe/authorizer/blob/master/authorizer.php#L1715-L1721

**Comment by mauroits** [comment]
It is from Membership 2 plugin, and it's https://mysite/ms-payment-return/paypalstandard

I have seen your link, but I'm not sure how to add my url, instead of feed, in this

function my_rsa_feed_access_override( $has_access ) {
			 *     global $wp;
			 *     // check query variables to see if this is the feed
			 *     if ( ! empty( $wp->query_vars['feed'] ) )
			 *       $has_access = true;
			 *     return $has_access;
			 *   }
			 *   add_filter( 'authorizer_has_access', 'my_rsa_feed_access_override' );

--

**Comment by figureone** [comment]
This should work in your theme:
```
// Allow access to PayPal IPN URL (Authorizer).
function my_paypal_ipn_access_override( $has_access ) {
	if ( '/ms-payment-return/paypalstandard' === $_SERVER['REQUEST_URI'] ) {
		$has_access = true;
	}

	return $has_access;
}
add_filter( 'authorizer_has_access', 'my_paypal_ipn_access_override' );
```
