### ISSUE TITLE
Set default permission for ldap group

### ISSUE THREAD

**Issue by Scriptkiddi** [uhm-coe/authorizer#56]
The idea is that one would another tab field in the options where a user could select an ldap group and what default user role that person should get so that one can install a system where users can login without the need for an administrator to look over registrations and depending on the person set the respective permission group
So I was wondering if thats a feature that would be wanted?

**Comment by figureone** [comment]
It is! It's on our roadmap to create a UI for correlating metadata from CAS or LDAP to WordPress roles. I'll leave this ticket open to track it.

FYI you can do this currently using hooks. See: https://github.com/uhm-coe/authorizer/issues/52

**Comment by figureone** [comment]
Merging into https://github.com/uhm-coe/authorizer/issues/75
