### ISSUE TITLE
if my wordpress is using a theme, and it has a self user login, authorizer will not work

### ISSUE THREAD

**Issue by supler** [uhm-coe/authorizer#58]
my wordpress is using a theme template, and the theme has self user login, when I configured authorizer for login, it will work well for wordpress self login interface http://xxx/wp-login.php, but when I tried to login use theme login interface to the first login , it will be fail, how to fix it?

**Comment by pkarjala** [comment]
You will need to modify your theme template to include Authorizer's login form code for the theme's login page.

This can be done by modifying the template or function that generates that page to add the sign in button. The relevant code that generates the button can be found at https://github.com/uhm-coe/authorizer/blob/master/authorizer.php#L2097 in the function “login_form_add_external_service_links()”.

The code that generates the URL for the link to CAS is located at https://github.com/uhm-coe/authorizer/blob/master/authorizer.php#L7622 in the function “modify_current_url_for_cas_login()”.

**Comment by supler** [comment]
thanks

**Comment by pkarjala** [comment]
Authorizer automatically hooks into the default WordPress login form without issue; any custom login forms are outside of our area of knowledge.

Please see https://codex.wordpress.org/Customizing_the_Login_Form for guidance on how to generate a custom login form.
