### ISSUE TITLE
Blank Page with CAS Authentication

### ISSUE THREAD

**Issue by maquisard** [uhm-coe/authorizer#60]
CAS authentication is successful then wordpress redirects to blank login page. The URL looks something like this: https://nadl-ctr.cs.tamu.edu/wp-login.php?external=cas&redirect_to=https%3A%2F%2Fnadl-ctr.cs.tamu.edu%2Fwp-admin%2F&ticket=ST-p5qmzPeGDtnUJYOoTyBduHQkijAIXVsw-cas-dev-1.syse.tamu.edu

![screenshot from 2018-10-03 17 44 17](https://user-images.githubusercontent.com/1199936/46443675-3074fc00-c734-11e8-8627-0d268859e19a.png)

Is there an easy way to troubleshoot this?

**Comment by pkarjala** [comment]
We occasionally run into this with stale cookies; can you try in incognito mode or a different browser and see if that resolves the issue?

In addition, try different values for `CAS server version`, and check your server's error logs to see if it is showing anything funny going on.

**Comment by pkarjala** [comment]
Hi @maquisard checking in if you still need assistance with this issue.

**Comment by maquisard** [comment]
Thank you for checking in.
I could not get the CAS working (blank page still) but I was able to use
the LDAP feature successfully. So I need no further assistance with this
issue.

Thank you

**Comment by pkarjala** [comment]
Sounds good, marking resolved!
