### ISSUE TITLE
Don't block page for unauthorized users while I set that page as private 

### ISSUE THREAD

**Issue by stgodjah** [uhm-coe/authorizer#61]
I set some pages as private, and some time its worked.
But after update Jetpack, unauthorized users got access to private pages. 
I check setting in plugin, all Ok. But when I try from another browser open that page, I **was not redirected** to login page.

**Comment by figureone** [comment]
Can you try disabling Jetpack and see if the private pages are blocked for anonymous users? If so, we'll try to track down the specific conflict with Jetpack.

**Comment by stgodjah** [comment]
Oh, sorry. But I already found solution. I set plugin authorizer to allow all pages, apply. And set to private pages, again. After that, operation, add my list of pages to private section. After re apply, plugin working correct. So, I cannot reproduce bug.

**Comment by figureone** [comment]
Thanks for the update. Please reopen the issue if you see it happen again!
