### ISSUE TITLE
About `auto redirect to cas server url`

### ISSUE THREAD

**Issue by aaronwu** [uhm-coe/authorizer#65]
When I hide Wordpress login，and enable cas login,
How can I make pages automatically jump to CAS on login page？
because i don't want click the `login by cas`, If other applications are logged in and then jump to this application, you should not need to log in？

**Comment by figureone** [comment]
It works that way if CAS is the only enabled External Service, and you've checked the `Immediately redirect to CAS` setting:

![screen shot 2018-11-30 at 8 40 11 am](https://user-images.githubusercontent.com/125274/49308194-b33bde00-f47b-11e8-8122-43fae4eaaebb.png)

**Comment by aaronwu** [comment]
That's great. I didn't even find out.
