### ISSUE TITLE
Unable to use SSL/StartTLS with self-signed certificate

### ISSUE THREAD

**Issue by olegblecher** [uhm-coe/authorizer#66]
Hi there!

Using Authorizer 2.8.6 with WP 4.9.8. It's a Debian 9 server with Apache.

I have no issues connecting using plain credentials against my DC, bus as soon as I activate TLS or try to connect to port 636, I simply cannot log in. "wrong username or password".

I've tried doing the following:

Add the following lines to `/etc/ldap/ldap.conf`:

```
TLS_REQCERT     never
TLS_CACERT      /usr/share/ca-certificates/extra/cert.crt
```

Even added the following to `/etc/apache2/apache2.conf`:

```
LDAPTrustedGlobalCert CA_BASE64 /usr/share/ca-certificates/extra/cert.crt
LDAPVerifyServerCert Off
```

Are you familiar with this issue? I would like to debug it, but I don't know what variable to use in `error_log( print_r( $variable_to_inspect, true ) );`... (thinking about this issue: https://github.com/uhm-coe/authorizer/issues/40).

Any help would be appreciated!

**Comment by olegblecher** [comment]
After activating LDAP-logging in authorizer.php I've managed to get some of that good ol' `Unable to start TLS: Connect error`

After a few hours of debugging I got tired. Reinstalled everything on Ubuntu 18 and it works like a charm. Would be interesting to know what causes the issue in Debian. But there is no problem in your plugin, so you can close this issue.

**Comment by figureone** [comment]
That's odd, it sounds like it's outright rejecting self-signed certs, but odd that there's a difference between Debian and Ubuntu. I'll see if I can find any details.

One other debugging step to try: the plugin silences errors in the `ldap_bind()` calls (that's what the `@` does before the function call). Might get more detailed errors in the web server logs if you take out the `@`.

**Comment by figureone** [comment]
I think this method may work:
https://stackoverflow.com/questions/3866406/need-help-ignoring-server-certificate-while-binding-to-ldap-server-using-php

If you get the time, try setting that config option in `ldap.conf`. If it works, I can try adding an Authorizer setting that adds `putenv( 'LDAPTLS_REQCERT=never' );` (along with the requisite warnings about security, etc.).

**Comment by olegblecher** [comment]
I had already found that Stackoverflow page and tried the recommendations listed there. adding `putenv( 'LDAPTLS_REQCERT=never' );` in authorizer.php (just before ldap_connect()) didn't help me at all. 

I'm starting to think that the Debian machine has its ldap.conf in some relatively unusual location..
