### ISSUE TITLE
Blank page if Authorizer can't download cacert.pem file

### ISSUE THREAD

**Issue by julienlusson** [uhm-coe/authorizer#70]
Hi,

I've got a problem with Authorizer: Error 500 when I tried to connect to wp-admin, the message in the log: "Cannot use object of type WP_Error as array in […]authorizer.php on line 1278"

The line:  
`new WP_Error( 'cannot_update_cacert', __( 'Unable to update outdated server certificates from https://curl.haxx.se/ca/cacert.pem.', 'authorizer' ) );`

In fact, we use a proxy with a whitelist of URL and `https://curl.haxx.se/ca/cacert.pem` is not allowed (for now). So the "error" is in fact OK, but the "500 error" not.

**Comment by figureone** [comment]
Thanks for testing that. I've never been happy with the dependency on downloading an up-to-date CA list from an external service, but think it's a good security practice.

I'll fix up the error handling so it doesn't break like you discovered, and instead make it show an admin notice if cacert.pem couldn't be downloaded from the cURL source.

**Comment by figureone** [comment]
@ipstenu from the WordPress Plugin Review team let us know that WordPress itself bundles a cacert bundle, at `/wp-includes/certificates/ca-bundle.crt`. So we're just going to use that one instead! That should avoid any problems with Authorizer trying to download its own updated copy from the cURL website.
https://github.com/uhm-coe/authorizer/commit/c11676cbd6b400d3b7ac26d057f5ae0726e9c494

This feature will be included in the next release, version 2.8.7.
