### ISSUE TITLE
Is there a way to customize the CAS URL?

### ISSUE THREAD

**Issue by netmas** [uhm-coe/authorizer#76]
Hi! Is it possible to customize the CAS URL?

This is the url I would need:
https://cas_domain_url/service-auth/login?service=https://my_domain_url

**Comment by figureone** [comment]
In Authorizer Settings:
`cas_domain_url` goes in CAS server hostname
`/service-auth` goes in CAS server path/context
`https://my_domain_url` is the WordPress root and doesn't need to be provided. The rest is automatically constructed via phpCAS and follows convention.
