### ISSUE TITLE
Add text domain and domain path in file header

### ISSUE THREAD

**Issue by Jojaba** [uhm-coe/authorizer#8]
In _authorizer.php_ header, you should add the following lines:
```
Text Domain: authorizer
Domain Path: /languages
```
Otherwise, your plugin will not be translatable on the wordPress description page (new feature added a few days ago, look to the right sidebar, you have a green button called "Translate Authorizer").
![authorizer_translation](https://cloud.githubusercontent.com/assets/606969/13980094/dbf9fc0a-f0dc-11e5-84de-14ef462c8877.png)

**Comment by figureone** [comment]
Cool thanks. I'll also spend some time today looking for remaining strings (and strings with variable substitution) to clean up the translatable phrases based on best practices here:
https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/

**Comment by figureone** [comment]
https://github.com/uhm-coe/authorizer/commit/38aaf6da469f4f765a7180c79bb9b443df735e97

**Comment by figureone** [comment]
FYI I've found and added a few more translatable strings: https://github.com/uhm-coe/authorizer/commit/b5c6c70f4979d6da6e71a5ede2a50e6805f23e27

I also generated a POT file if that makes it easier to identify the new strings.
https://github.com/uhm-coe/authorizer/commit/a7e71147dd6175db76fe838e75564836f867a2e0

**Comment by Jojaba** [comment]
OK, thanks. A few more translatable strings ? A bunch of them, yes ;p
I'll translate them today and send them (I don't know how for the moment) to ask you to add them into authorizer...

**Comment by Jojaba** [comment]
Done!
I saw some typos and some inconsistency (you talk about "one user" then you say "their" for example) on original strings (en), I would suggest to proofread them ;)
I hope you can add this translation for the next release. Thansk in advance. Joël.
[Authorizer-2.5.0-fr_FR-translation.zip](https://github.com/uhm-coe/authorizer/files/188448/Authorizer-2.5.0-fr_FR-translation.zip)

**Comment by figureone** [comment]
You are awesome, thanks! I just released version 2.5.0 with these updates, please let me know if you encounter any problems.

Regarding "their," I consider myself open to the evolution of language. ;)
http://www.merriam-webster.com/video/the-awkward-case-of-his-or-her
