### ISSUE TITLE
Provide ability to specify logout URL

### ISSUE THREAD

**Issue by pdvsingh** [uhm-coe/authorizer#80]
We are using Authorizer with Gluu. When a user logs out of Wordpress, they are transferred to a Gluu logout page. I have seen that some other plugins provide the ability to specify log out URL. This setting would help us take the user to the WP homepage instead of a default logout page on Gluu.

**Comment by figureone** [comment]
I think this should work, but I'm not sure on your implementation details (I'm unfamiliar with Gluu, or how you have it integrated with Authorizer). 

Authorizer doesn't interfere with normal WordPress logouts; it just hooks into `wp_logout` to also logout out of Google or CAS when the user logs out of WordPress. So I think you should be able to generate any logout links using `wp_logout_url()` and include a `redirect_to` param for where the user should be taken after logging out.
https://developer.wordpress.org/reference/functions/wp_logout_url/

For example, a logout URL with redirect would look like:
```
https://example.com/wp-login.php?action=logout&redirect_to=https%3A%2F%2Fexample.com%2Fyour-custom-location%2F&_wpnonce=abcdef1234
```

**Comment by pkarjala** [comment]
Hi @pdvsingh We are going to mark this issue closed, as we have not received any updates since the last comment.  If you require any further assistance, please re-open this issue!
