### ISSUE TITLE
Redirect after login

### ISSUE THREAD

**Issue by ocager** [uhm-coe/authorizer#82]
Hello,

I'm using Authorizer since years for our Corporate Intranet page by using our SSO service via CAS. The Business Owner of this service reported several times a redirect issue after login by following this procedure:

1. User clicks a link in an application **www.site.com/news** while no browser is opened
2. Browser starts and is trying to open **www.site.com/news**
3. As the user is not logged in, he will be automatically logged on via Authorizer
4. The user will see finally **www.site.com** (the startpage)

Is there a possibility that there will be a redirect to the initial requested page (**www.site.com/news**) after the login is performed by Authorizer?

Please find following the preferences used with Authorizer.

Thanks,
Oliver

![AUTH_01_LoginAccess](https://user-images.githubusercontent.com/30630832/61451637-225a3a00-a95a-11e9-986d-0cc222e14f38.png)
![AUTH_02_PublicAccess](https://user-images.githubusercontent.com/30630832/61451640-225a3a00-a95a-11e9-8fb3-d686dc785782.png)
![AUTH_03_ExternalService](https://user-images.githubusercontent.com/30630832/61451643-22f2d080-a95a-11e9-925e-9b423c0df985.png)
![AUTH_04_Advanced](https://user-images.githubusercontent.com/30630832/61451644-22f2d080-a95a-11e9-9dd4-13c341ca69a4.png)

**Comment by figureone** [comment]
Aloha, it is supposed to work that way (redirect to user's previous page), done here:
https://github.com/uhm-coe/authorizer/blob/master/src/authorizer/class-authorization.php#L612

The procedure should be:
1. User follows a link to https://www.site.com/news
2. Browser opens page, and Authorizer redirects to https://www.site.com/wp-login.php?redirect_to=%2Fnews%2F
3. User clicks "Sign in with CAS" and logs in
4. User is redirected back to https://www.site.com/news after successfully logging in

Can you check that the `redirect_to` param exists when you're viewing the wp-login.php page?

If it's not getting set, then something about your server environment is preventing Authorizer from getting the URI to redirect to:
https://github.com/uhm-coe/authorizer/blob/master/src/authorizer/class-authorization.php#L586

**Comment by ocager** [comment]
Hi,

thanks for the quick reply. Following your description, it seems that step 2 is different:

1. User follows a link to https://www.site.com/news
2. Browser opens page, and Authorizer redirects to https://www.site.com/wp-login.php?redirect_to=**home**

Don't really understand where **home** comes from. So I've viewed wp-login.php and just looked for redirect_to, I found 58 results. I've attached it. Might it be possible that the change comes from the CAS server?

[wp-login.zip](https://github.com/uhm-coe/authorizer/files/3409438/wp-login.zip)

**Comment by ocager** [comment]
Hi figureone,

you are right... someone set the redirect_to param. Thanks a lot!
