### ISSUE TITLE
Pls clarify access settings for Multisite

### ISSUE THREAD

**Issue by blepharisma** [uhm-coe/authorizer#83]
Hi,

I'm wondering if someone can clarify the settings for Multisite in the 'Access Lists' panel for me. 

1. Who can log in to sites in this network?  - If I select "all authenticated users", our CAS users can login to the network, but this doesn't determine whether they can login to individual blog sites, correct? I don't want to restrict things so far as to add an Approved Users list - I just want blog admins to be able to add existing users.

2. Who can view sites in this network? - If I select 'Everyone can see the site', does this force all sites to be public? We have an additional plugin that allows blog admins to control the visibility of their own sites. I just want to be sure that this setting doesn't contravene their ability to do so.

Essentially, we are looking for the plugin to provide CAS authentication and user provisioning - we aren't looking to restrict who in the network can be added to which sites (the blog admins should be able to do that, without giving them 'create' access).

Thanks for your help!

Cheers,
Stephanie

**Comment by figureone** [comment]
> 1. Who can log in to sites in this network? - If I select "all authenticated users", our CAS users can login to the network, but this doesn't determine whether they can login to individual blog sites, correct? I don't want to restrict things so far as to add an Approved Users list - I just want blog admins to be able to add existing users.

"All authenticated users" will create new WordPress accounts for any valid login from CAS (or log them into their existing WordPress account with the same email). If set in multisite settings, this applies to all individual blogs in the network. It sounds like you actually want "Only approved users," which will create a "Pending" user entry for any new logins from CAS that don't already have an associated WordPress account.

Also, note that the Approved Users list in multisite settings applies to all sites in the network: users in that list will be able to log in with their external service credentials on any site in the network.

> 2. Who can view sites in this network? - If I select 'Everyone can see the site', does this force all sites to be public? We have an additional plugin that allows blog admins to control the visibility of their own sites. I just want to be sure that this setting doesn't contravene their ability to do so.

Selecting "Everyone can see the site" basically means Authorizer won't try to restrict access. This leaves it at the WordPress default (all pages/posts are publicly viewable). Nothing extra is done, so this should be what you want if you have another plugin enforcing access.

One final note: individual blogs all have a setting to override the multisite settings and configure Authorizer just for that site. This is helpful if you have unique login or user settings for certain sites.
`Authorizer Settings > Advanced > Configure this site independently (don't inherit any multisite settings)`

**Comment by blepharisma** [comment]
Thank you for the clarification - I appreciate it.

Have a great weekend!
