### ISSUE TITLE
Allow LDAP server to reference domain name

### ISSUE THREAD

**Issue by basildane** [uhm-coe/authorizer#85]
LDAP login is working great, but only if I specify a specific LDAP server.
Example: **ldap://myserver.mydomain.com**

This will fail if **myserver** is unavailable for some reason.
A better way is to use **ldap://mydomain.com**

Active directory will give you a list of LDAP servers and you get full redundancy.  I have not been able to get this to work with Authorizer.

**Comment by figureone** [comment]
Do you know if this is a feature specific to Active Directory, and can you link to any docs?

We're trying to maintain compatibility between LDAP offerings (openldap, AD, etc.), so that would be the main consideration.

**Comment by basildane** [comment]
I read the RFC and don't specifically see this.  But that's how we do it at work (50,000 users).  Here's another idea, is there a way for me to specify at least one additional server?  Just having one is a problem.  It's going to be a problem for everyone, I expect.

**Comment by figureone** [comment]
That sounds good, I've seen that elsewhere and it should work across all LDAP servers. We will get that integrated into the next version and keep you updated here. Thanks!

**Comment by figureone** [comment]
https://github.com/uhm-coe/authorizer/commit/073a533cdfa4685cdc90042f19904bd881cdeeb0

**Comment by figureone** [comment]
Version 2.9.9 has been released with the feature. You can now add multiple LDAP hosts to the `LDAP Host` settings field (one per line). Thanks!

Changelog:
https://wordpress.org/plugins/authorizer/#developers

**Comment by basildane** [comment]
Great news!  Thank you.
