### ISSUE TITLE
no LDAP-login since version 2.9.9

### ISSUE THREAD

**Issue by MamoulianDelacroix** [uhm-coe/authorizer#86]
Hi everyone,

since I updated to version 2.9.9 a few days ago. I can't login via LDAP anymore.
Sadly I can't find any error logs or anything simillar for troubleshooting.

We are using Wordpress in Version 5.3 and our LDAP-server is an Micro Focus eDir.
Bevor version 2.9.9 everything was fine.

Are there any troubleshooting logs?

**Comment by figureone** [comment]
We released a small change in version 2.9.9 to allow multiple LDAP hosts; not sure why that caused a problem.

If you need to restore functionality immediately, you can revert to the previous version:
https://downloads.wordpress.org/plugin/authorizer.2.9.8.zip

**Comment by figureone** [comment]
Another thing to check: we added a new check `is_valid_domain_name()` on the LDAP hosts, it's possible your LDAP host is failing that check. Can you try just adding `return true;` to that function here:
https://github.com/uhm-coe/authorizer/blob/master/src/authorizer/class-helper.php#L384-L399
and see if it fixes things? Or share what your LDAP host looks like (you can anonymize it if needed, I just need the general form to test.

**Comment by figureone** [comment]
We reverted the `is_valid_domain_name()` check, so all LDAP URIs should work again after upgrading to version 2.9.10.

https://github.com/uhm-coe/authorizer/commit/1eb05bc865c4b452d6e5c2e32c0fba884024b0f8

**Comment by MamoulianDelacroix** [comment]
> We reverted the `is_valid_domain_name()` check, so all LDAP URIs should work again after upgrading to version 2.9.10.

Thank you a lot. With 2.9.10 everything is back to normal!
