### ISSUE TITLE
Restriction to group

### ISSUE THREAD

**Issue by Migo2468** [uhm-coe/authorizer#88]
Hi I have ldap server based on Synology. 

I have 2 groups:
1. Users
```
dn: cn=users,cn=groups,dc=ldap,dc=domain,dc=com
cn: users
gidNumber: 1000001
member: uid=u1,cn=users,dc=ldap,dc=domain,dc=com
member: uid=u2,cn=users,dc=ldap,dc=domain,dc=com
member: uid=u3,cn=users,dc=ldap,dc=domain,dc=com
memberUid: u1
memberUid: u2
memberUid: u3
```

2. group1:
```
dn: cn=group1,cn=groups,dc=ldap,dc=domain,dc=com
gidNumber: 1000003
member: uid=u1,cn=users,dc=ldap,dc=domain,dc=com
member: uid=u2,cn=users,dc=ldap,dc=domain,dc=com
member: uid=admin,cn=users,dc=ldap,dc=domain,dc=com
memberUid: u1
memberUid: u2
memberUid: admin
cn: group1
```

How can I restriction to `group1`?
When i config my `LDAP Search Base` to:
- cn=users,dc=ldap,dc=idomain,dc=com - connect to all users
- cn=group1,dc=ldap,dc=idomain,dc=com - I have error and user is not login

Error
```

Warning: ldap_search(): Search: No such object in wp-content/plugins/authorizer/src/authorizer/class-authentication.php on line 677

Warning: ldap_get_entries() expects parameter 2 to be resource, bool given in wp-content/plugins/authorizer/src/authorizer/class-authentication.php on line 682
```

**Comment by figureone** [comment]
You'll want to leave your search base as `cn=users,...`, and then hook into `authorizer_ldap_search_filter` to further restrict to that subset of users:
https://github.com/uhm-coe/authorizer/blob/master/src/authorizer/class-authentication.php#L662-L672

It should look something like this (assuming you've got the memberOf overlay enabled):
```
add_filter( 'authorizer_ldap_search_filter', function ( $search_filter, $ldap_uid, $username ) {
	return "(&(memberOf=cn=group1,dc=ldap,dc=idomain,dc=com)$search_filter)";
}, 10, 3 );
```

See for more details:
https://wordpress.org/support/topic/ldap-login-wordpress-docker/#post-12066380

At some point in the future we plan on adding a UI option to change this (so you don't have to use the hook).

**Comment by Migo2468** [comment]
@figureone thanks

form me work this snippet:
`add_filter( 'authorizer_ldap_search_filter', function ( $search_filter, $ldap_uid, $username ) {
	return "(&(memberOf=cn=group1,cn=groups,dc=ldap,dc=domain,dc=com)$search_filter)";
}, 10, 3 );`
