### ISSUE TITLE
empty $wp->request ?

### ISSUE THREAD

**Issue by ablivio** [uhm-coe/authorizer#90]
Hello,

What is the purpose of the following snippet (533-535) in class-authorization.php ?
```
		// Check to see if the requested page is public. If so, show it.
		if ( empty( $wp->request ) ) {
			$current_page_id = 'home';
```
On my site, it breaks the behavior and access is denied even if the page is set as public.
When I disable it (using "false && empty( $wp->request)"), I get a proper result.

**Comment by figureone** [comment]
The snippet above detects empty requests (i.e., they don't have query vars or any params to filter to), which typically means it's a request for the site's home page.

`$wp->request` is set in `WP::parse_request()` here:
https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp.php#L192-L205
https://developer.wordpress.org/reference/classes/wp/parse_request/

Maybe there's something about your setup that modifies the WordPress environment instance? Do you have any other theme/plugin code that hooks into `parse_request`?
https://developer.wordpress.org/reference/hooks/parse_request/

**Comment by figureone** [comment]
Closing, please reopen if you have further details!
