### ISSUE TITLE
User Switching not longer working with Authorizer Version 2.9.11

### ISSUE THREAD

**Issue by ocager** [uhm-coe/authorizer#91]
Hi,

since the release 2.9.11, the plugin [User Switching](https://wordpress.org/plugins/user-switching/) is no longer working (more information about the behavior [here](https://github.com/johnbillion/user-switching/issues/50)). I've tested previously available versions from 2.8.8 to 2.9.11 and can confirm that the problem started with the current version (2.9.11). For the first time, I thought the reason is the plugin User Switching itself, but after a further investigation, I found out that the issue is linked to Authorizer.

Following your change log for version 2.9.11, there were many changes included, but I'm not the technical expert to identify if that behavior is wanted or not. Do you have an idea why User Switching is not working?

Regards
oca

**Comment by figureone** [comment]
WordPress version 5.3 changed the behavior of the `wp_logout` filter, which caused us to switch to `clear_auth_cookie` to be able to log out CAS users:
https://github.com/uhm-coe/authorizer/commit/586eebc9636078f04c2f6cd61769f3e055d22adc

Here's the trac ticket about it:
https://core.trac.wordpress.org/ticket/35488#comment:11

And one of our support requests:
https://wordpress.org/support/topic/logout-does-not-work-2/

Can you try editing `class-wp-plugin-authorizer.php` as shown above to switch back to the `wp_logout` filter and see if that's the cause? If so, we'll need to investigate what User Switching is doing to change the current user.

**Comment by ocager** [comment]
> Can you try editing class-wp-plugin-authorizer.php as shown above to switch back to the wp_logout filter and see if that's the cause? If so, we'll need to investigate what User Switching is doing to change the current user.

I can confirm that changing back to _wp_logout_ filter recovers the functionality of the plugin _User Switching_.

**Comment by figureone** [comment]
Aloha, version 2.9.12 is out now with a fix, please test to see if it works for you.

**Comment by ocager** [comment]
Hi Paul, I installed the new version and tested successfully. Thanks a lot for the quick reaction and fix. Best!
