### ISSUE TITLE
Hidden Site with Forced CAS login and hidden WP login goes into redirect loop

### ISSUE THREAD

**Issue by fotan** [uhm-coe/authorizer#95]
Or is this a feature?  Maybe I'm not understanding the thought process?

**Comment by fotan** [comment]
Hiding the site doesn't seem to be the issue.

**Comment by fotan** [comment]
I think I answered my own question.  It goes into this loop when you're logged in using the no-CAS switch and you are dumb enough to set up the no-CAS user using the same email address as CAS has for you.  If you change the email address for the no-CAS user, it works as expected.

**Comment by figureone** [comment]
Glad you figured it out!
