### ISSUE TITLE
Authorizer scripts (css / JS) not loaded in the network admin

### ISSUE THREAD

**Issue by julienlusson** [uhm-coe/authorizer#97]
Hi,

Authorizer scripts, both js and css, aren't loaded in the network admin. In a site admin, it's OK.

**Comment by figureone** [comment]
Interesting; we see it loading normally in network admin on our sites. Do you have any modifications to vanilla WordPress, like moving the wp-content directory?

![Screen Shot 2020-11-30 at 9 02 58 AM](https://user-images.githubusercontent.com/125274/100652344-e32c4f00-32ea-11eb-88b5-febdc0636981.png)

**Comment by julienlusson** [comment]
Sorry, I've not put the version number of Authorizer.

In Authorizer 2.*, the files are loaded, but not in 3.0.2 (with no other plugin or theme activated).

**Comment by figureone** [comment]
I see it now, thanks! We will get a fix out shortly.

**Comment by figureone** [comment]
Aloha, we created version 3.0.3 that has the fix for this. Thanks for the report!
https://github.com/uhm-coe/authorizer/commit/72283918281f522788ea512f97aac7e6b25c6eae
